package kz.edu.biletflow.backend.mappers;

import kz.edu.biletflow.backend.dtos.RegisterUserRequest;
import kz.edu.biletflow.backend.dtos.UserResponse;
import kz.edu.biletflow.backend.entities.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface UserMapper {
    @Mapping(target = "id", ignore = true) // Generated by DB
    @Mapping(target = "passwordHash", ignore = true) // We will hash and set this manually in the Service
    @Mapping(target = "role", constant = "ATTENDEE") // Default role assigned safely by the backend
    @Mapping(target = "events", ignore = true) // Ignore relationships on creation
    @Mapping(target = "createdAt", ignore = true) // Let JPA handle the timestamp
    @Mapping(target = "verificationStatus", ignore = true)
    User toEntity(RegisterUserRequest request);

    @Mapping(target = "id", ignore = true)
    UserResponse toDto(User user);
}
