spring:
  application:
    name: backend-biletflow
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET:local_development_secret_key_must_be_at_least_32_chars_long______}
    tokenExpiration: 864000
